# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope', models.IntegerField()),
                ('par', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('strokes', models.IntegerField()),
                ('putts', models.IntegerField()),
                ('fairways_hit', models.IntegerField()),
                ('gir', models.IntegerField()),
                ('equistrokes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GBGolf.Course', to_field='course')),
            ],
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drdist', models.IntegerField()),
                ('dracc', models.IntegerField()),
                ('par3tee', models.IntegerField()),
                ('lngdist', models.IntegerField()),
                ('lngacc', models.IntegerField()),
                ('shtdist', models.IntegerField()),
                ('shtacc', models.IntegerField()),
                ('pitch', models.IntegerField()),
                ('chip', models.IntegerField()),
                ('putt', models.IntegerField()),
                ('penal', models.IntegerField()),
                ('coursemgmt', models.IntegerField()),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GBGolf.Round', to_field='date')),
            ],
        ),
    ]
