# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='holesplayed',
            field=models.IntegerField(default=18),
        ),
    ]
