# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0002_round_holesplayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuttPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('makes', models.IntegerField()),
            ],
        ),
    ]
