# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0003_puttpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeDrill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drill', models.CharField(max_length=40)),
                ('club', models.CharField(max_length=10)),
                ('balls_hit', models.IntegerField()),
            ],
        ),
    ]
