# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0006_auto_20170412_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedrill',
            name='drill',
            field=models.CharField(choices=[('Warmup', 'Warmup'), ('Toe/Heel/Center Strike', 'Toe/Heel/Center Strike'), ('Toe/Heel Setup', 'Toe/Heel Setup'), ('Gate Strike', 'Gate Strike'), ('Toe or Heel Constraint', 'Toe or Heel Constraint'), ('Step Drill', 'Step Drill'), ('Cooldown', 'Cooldown')], default='Toe/Heel/Center Strike', max_length=40),
        ),
    ]
