# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0007_auto_20170414_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedrill',
            name='drill',
            field=models.CharField(choices=[('Warmup', 'Warmup'), ('Toe/Heel/Center Strike', 'Toe/Heel/Center Strike'), ('Toe/Heel Setup', 'Toe/Heel Setup'), ('Gate Strike', 'Gate Strike'), ('Toe or Heel Constraint', 'Toe or Heel Constraint'), ('Step Drill', 'Step Drill'), ('Grass Divot Drill', 'Grass Divot Drill'), ('Sand Divot Drill', 'Sand Divot Drill'), ('Ball Position Divot', 'Ball Position Divot'), ('Towel Drill', 'Towel Drill'), ('Cooldown', 'Cooldown')], default='Toe/Heel/Center Strike', max_length=40),
        ),
    ]
