# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGolf', '0010_auto_20170417_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipdrill',
            name='drill',
            field=models.CharField(choices=[('Home Mat Chip', 'Home Mat Chip'), ('HH Close Hole Chip', 'HH Close Hole Chip'), ('HH Far Hole Chip', 'HH Far Hole Chip'), ('Lob Shot', 'Lob Shot'), ('Bump and Run', 'Bump and Run'), ('Bunker Shot', 'Bunker Shot'), ('3 Coin Chip', '3 Coin Chip')], default='Home Mat Chip', max_length=40),
        ),
        migrations.AlterField(
            model_name='rangedrill',
            name='drill',
            field=models.CharField(choices=[('Warmup', 'Warmup'), ('Toe/Heel/Center Strike', 'Toe/Heel/Center Strike'), ('Toe/Heel Setup', 'Toe/Heel Setup'), ('Gate Strike', 'Gate Strike'), ('Toe or Heel Constraint', 'Toe or Heel Constraint'), ('Step Drill', 'Step Drill'), ('Grass Divot Drill', 'Grass Divot Drill'), ('Sand Divot Drill', 'Sand Divot Drill'), ('Ball Position Divot', 'Ball Position Divot'), ('Towel Drill', 'Towel Drill'), ('3-Tee Drill', '3-Tee Drill'), ('Coin Tee Drill', 'Coin Tee Drill'), ('Variable Height Tee Drill', 'Variable Height Tee Drill'), ('Cooldown', 'Cooldown')], default='Toe/Heel/Center Strike', max_length=40),
        ),
    ]
