# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fiththird_check', models.DecimalField(decimal_places=2, max_digits=8)),
                ('huntington_check', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fifththird_save', models.DecimalField(decimal_places=2, max_digits=8)),
                ('huntington_save', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capone_save', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amex_save', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buckeye_invest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deacon_invest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('four57_retire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('four01_retire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roth_retire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('opers_retire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('justin_car', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kat_car', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_home', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pubstudent_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('privstudent_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_mortgage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amex_credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discover_credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capone_credit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
