# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBFinance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthbal',
            old_name='fiththird_check',
            new_name='fifththird_check',
        ),
    ]
