# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBFinance', '0002_auto_20170311_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthInc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('huntington_interest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fifththird_interest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capone_interest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amex_interest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('schwab_interest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('schwab_dividends', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
