# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBFinance', '0004_auto_20170319_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthbal',
            old_name='four01_retire',
            new_name='four01_retirebal',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='four57_retire',
            new_name='four57_retirebal',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='opers_retire',
            new_name='opers_retirebal',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='roth_retire',
            new_name='roth_retirebal',
        ),
    ]
