# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GBFinance', '0005_auto_20170322_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthbal',
            old_name='four01_retirebal',
            new_name='four01_retire',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='four57_retirebal',
            new_name='four57_retire',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='opers_retirebal',
            new_name='opers_retire',
        ),
        migrations.RenameField(
            model_name='monthbal',
            old_name='roth_retirebal',
            new_name='roth_retire',
        ),
    ]
