# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBFinance', '0006_auto_20170322_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbal',
            name='robinhood_invest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthinc',
            name='robinhood_investments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
